baseurl = "https://example.com/"
languageCode = "en-us"
title = "Hugo Theme Yuki"
theme = "yuki"
author = "Cyris"
copyright = ""
paginate = 10
themesDir = "themes"
baseURL = ""
publishDir = "public"

[params]
mainSections = [ "post" ]
author = "Author"
description = "Short description"
authorwebsite = "https://example.com/"
favicon = "images/logo.png"
logo = "images/logo.png"
avatar = ""
displayImg = "images/display.png"
snsTitle = "Social"
ga_api_key = "Your Google Analytics tracking id"

[[menu.nav]]
name = "HOME"
url = "/"
weight = 1

[[menu.nav]]
name = "BLOG"
url = "/post"
weight = 2

[[menu.nav]]
name = "ABOUT"
url = "/about"
weight = 3

[[menu.nav]]
name = "TAGS"
url = "/tags/"
weight = 4

[[menu.social]]
name = "Example-1"
url = "/"
weight = 1

[[menu.social]]
name = "Example-2"
url = "/"
weight = 2

[[menu.social]]
name = "Example-3"
url = "/"
weight = 3
